### ISSUE TITLE
Releases gone?

### ISSUE THREAD

**Issue by IzzySoft** [JunioJsv/minimum#11]
It seems you've removed all releases. Will they return? Not everyone can (or wants to) use PlayStore, so releases was the place folks without Google stuff could obtain the APKs.

**Comment by JunioJsv** [comment]
Hello, I just removed the old releases because the app is now available on the Google Play Store. However, when I have some time, I'll create a pipeline to generate the APK from the commit, alright? If you'd like, you can help me with that part in a pull request.

**Comment by IzzySoft** [comment]
Thanks @JunioJsv! And as outlined, not everyone has access to PlayStore: some are locked out by censorship of their location, some by Google, some avoid Google & Co for privacy reasons. So your app is also available [in my repo](https://apt.izzysoft.de/packages/juniojsv.minimum/), from where it can be installed and kept up-to-date using an [F-Droid client](https://android.izzysoft.de/applists/category/named/apps_markets#group_1181) of choice. But in order to provide that possibility, I need the APK. The updater in my repo was fetching it from your releases until recently – and it cannot (and should not) take them from Google's walled garden.

I'm no Android dev, nor am I familiar with Github's pipelines/CI/workflows – so I unfortunately cannot help you with a PR there, sorry.

**Comment by JunioJsv** [comment]
I just released a new version with the latest Google Play Store update. I believe it might be incompatible with previous versions because I had to change the signing key.

I'll resume posting the versions here on GitHub.

**Comment by IzzySoft** [comment]
A changed signing key indeed is an issue, see [How to keep your key safe and what measures to take for the event of loss?](https://f-droid.org/2023/09/03/reproducible-builds-signing-keys-and-binary-repos.html#lessons-learned-2-how-to-keep-your-key-safe-and-what-measures-to-take-for-the-event-of-loss) What happened in your case, and do you still have access to the original key?

**Comment by IzzySoft** [comment]
@JunioJsv ^^ (in case the notification got lost for that comment – it does that sometimes at Github currently)

**Comment by JunioJsv** [comment]
I think I still have the old key

**Comment by IzzySoft** [comment]
That would be great! If you find it, there'd be two possible approaches:

* you switch back to that "old key" in general
* you just provide the APK of the latest release twice, once signed with the old and once with the new key – but both being built from the same recent commit. Then these APKs can be compared (there are tools for that) and should match, except for the signature – which would prove you're holding both keys and thus the transition to the new one is "legit".

**Comment by JunioJsv** [comment]
Hello, I just released a new version on GitHub, with 2 APKs, one with the old signing key and another with the new one.

**Comment by JunioJsv** [comment]
There were some errors occurring, I had to remove the apks, but I will send them again later

**Comment by IzzySoft** [comment]
Thanks, will wait for your next ping then.

**Comment by JunioJsv** [comment]
I just uploaded the [apks](https://github.com/JunioJsv/minimum/releases)

**Comment by IzzySoft** [comment]
Are you sure both APKs were built from the same commit, and differ only in the signature? They show massive differences here (files only being in one but not in the other, resources different etc). Also size differs by ~65k. Maybe just build the APK once, then copy the unsigned APK file and sign one copy with the old and the other with the new key?

Oof, and what is that with the new one?

```
Signer #1 certificate DN: CN=Android, OU=Android, O=Google Inc., L=Mountain View, ST=California, C=US
Signer #1 certificate SHA-256 digest: cbb6eed72891f9cc2a74230cc9e0325adf1a3dc2a5ec833b70f449c0da51c786
Signer #1 certificate SHA-1 digest: b3ec126faf8e3500f9dbd6b9ee7fd041de379844
Signer #1 certificate MD5 digest: 756ecb752783faa82c34f3b038ab9239
Signer #1 key algorithm: RSA
Signer #1 key size (bits): 4096
```

That's not signed by you. Further:

```
SigningBlock blobs:
-------------------
0x6dff800d (SOURCE_STAMP_V2_BLOCK; GOOGLE)
```

See [BLOBs in APK signing blocks](https://android.izzysoft.de/articles/named/iod-scan-apkchecks?lang=en#blobs) for details on that. Sorry, but I cannot accept that APK. Any chance to keep the one signed with your own key available, also with future releases?

**Comment by JunioJsv** [comment]
the app with the new signature was generated from the aab that I sent to the google play store, this is probably what is causing these discrepancies, the aab was signed with my new signature but the apk was signed by google

**Comment by JunioJsv** [comment]
I will release the versions with github with my old key

**Comment by JunioJsv** [comment]
Okay, I just replaced the Github releases apks with versions signed with the old key

**Comment by IzzySoft** [comment]
Thanks! Initializing with the latest APK manually now (manually because the version in my repo has `versionName: 1.12` – which is semantically higher than the current 1.6.0, according to [semver](https://semver.org/) – you obviously switched to semver meanwhile) … OK, that worked out. After the initial

```
$ iod repo get juniojsv.minimum
juniojsv.minimum: looking for 'https://api.github.com/repos/JunioJsv/minimum/releases'
juniojsv.minimum: checking tag 'v1.6.0'
juniojsv.minimum: lastRelNo set to 'v1.6.0', checking for files
juniojsv.minimum: Upstream file date (2024-03-25 00:39) is newer than ours (2020-05-24 02:00).
juniojsv.minimum: returning ['v1.6.0','https://github.com/JunioJsv/minimum/releases/download/v1.6.0/juniojsv.minimum-v1.6.0-release.apk',1711323562]
juniojsv.minimum: 1.12 up-to-date.
```

(where it based on v1.12) I now get

```
$ iod repo get juniojsv.minimum
juniojsv.minimum: looking for 'https://api.github.com/repos/JunioJsv/minimum/releases'
juniojsv.minimum: checking tag 'v1.6.0'
juniojsv.minimum: lastRelNo set to 'v1.6.0', checking for files
juniojsv.minimum: Upstream file date (2024-03-25 00:39) not newer than ours (2024-03-25 01:12), skipping.
juniojsv.minimum: returning local appdata as ['1.6.0','',0]
juniojsv.minimum: 1.6.0 up-to-date.
```

So it bases on v1.6.0 now (though 1.12 is still present), which means future updates should work out.

While on it I also updated screenshots and description, based on your app's PlayStore listing. If you want to I can send you a PR with the metadata in Fastlane format (you can use my [Fastlane Cheat Sheet](https://gitlab.com/-/snippets/1895688) then to build on this), so you can keep it updated yourself and changes to it would be pulled together with new releases – just let me know.

Thanks for your help and support with this! Guess we can close the issue then?
