### ISSUE TITLE
Hide apps

### ISSUE THREAD

**Issue by Pantyhose-X** [JunioJsv/minimum#12]
* Hide apps
> Search won't show hide apps
* Show hidden apps 
> In Settings > Preferences > Show hidden apps 

## other
 Support Setting the background image (wallpaper)

**Comment by JunioJsv** [comment]
When I have free time, I will definitely implement this feature of being able to hide some apps

**Comment by JunioJsv** [comment]
Hello, I have just released a new version with the feature to hide apps, along with several other improvements. Here is the link: https://github.com/JunioJsv/minimum-flutter/releases/tag/v2.0.0
