### ISSUE TITLE
Home screen

### ISSUE THREAD

**Issue by NaN-Sz** [JunioJsv/minimum#13]
I know it seems a little outside the scope of the project, but there are a few widgets I use and a home screen would be great.
 Maybe with an option to deactivate (for the more minimalist people).

**Comment by JunioJsv** [comment]
I'll think about how to add this functionality, I'm open to ideas

**Comment by NaN-Sz** [comment]
Hi, here's an image made in a photo editor of what the home screen could look like.

![pc2.jpg](https://github.com/JunioJsv/minimum/assets/120607988/8d0f5cbd-cf6e-44d8-8fc3-1eb81ea1aae1)

Or with button to open the app drawer.

![pc3.jpg](https://github.com/JunioJsv/minimum/assets/120607988/d3887185-41cc-46bc-bcb3-3490f97aa075)

Well, it's just a suggestion :)

**Comment by JunioJsv** [comment]
I think it looks good, I'll try to implement this soon after resolving the issue #12

**Comment by Pantyhose-X** [comment]
No I think Home Screen is bad, you also need to drag the app to the Home screen

There are a lot of Home Screen App For example `Simple Launcher` `Shade Launcher
` `Lawnchair` `Neo Launcher`

**Comment by Pantyhose-X** [comment]
###  Add "Tab Page"  is a great option!
Drag the app to the "new tab page"
