### ISSUE TITLE
Multiple instances of apps

### ISSUE THREAD

**Issue by icnocop** [JunioJsv/minimum#8]
Hi.

Thank you for Minimum.

I noticed duplicate instances of my installed apps.

Steps to reproduce:
1. Install Minimum on my Android device.
2. Launch Minimum.
3. Launch Google Play Store from Minimum and install Chrome for example
4. Go back to Minimum
5. Notice multiple instances of Chrome are listed

![20200803_143026](https://user-images.githubusercontent.com/507649/89229598-92078b00-d596-11ea-9f0b-b0e1a952fbc1.jpg)

Any ideas?

Thank you.

**Comment by JunioJsv** [comment]
once in a while this also happens to me, I will try to solve

**Comment by JunioJsv** [comment]
[juniojsv.minimum-v1.2.3-release.apk.zip](https://github.com/JunioJsv/minimum/files/5019331/juniojsv.minimum-v1.2.3-release.apk.zip)

Test this version, I think I managed to solve

**Comment by icnocop** [comment]
Hi.

Thank you for the quick reply.

Unfortunately, when I try to install it, I get the error `INSTALL_PARSE_FAILED_NO_CERTIFICATES`.

```
>adb install C:\Users\MyName\Downloads\juniojsv.minimum-v1.2.3-release.apk
Performing Push Install
C:\Users\MyName\Downloads\juniojsv.m...d. 499.6 MB/s (964350 bytes in 0.002s)
        pkg: /data/local/tmp/juniojsv.minimum-v1.2.3-release.apk
Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES]
```

Any ideas?

Thank you.

**Comment by JunioJsv** [comment]
Put on cmd: "adb uninstall juniojsv.minimum" and install the version I sent

**Comment by icnocop** [comment]
Thank you.

I had uninstalled the previous app, but I still received the same error.

I'm trying to install the apk on Android 6.0.1 with armeabi-v7a.

I can install the apk in the artifact generated from the build https://github.com/icnocop/minimum/runs/943092121.

I opened PR #9 which contains a CI build script that automatically builds the apk, triggered when code is pushed to the master branch.

I'm wondering if you can merge the PR and then push your code?

Thank you.

**Comment by JunioJsv** [comment]
the changes are already in the repository, thanks for the PR

**Comment by icnocop** [comment]
Thank you!

It worked!

I installed Google Photos and only one instance of that app shows up.
